export const SET_NEW_USER = 'SET_NEW_USER'
export const REMOVE__COOKIE = 'REMOVE__COOKIE'

export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT'
export const GET__ALL_PROJECTS = 'GET__ALL_PROJECTS'
export const GET_CURRENT_PROJECT = 'GET_CURRENT_PROJECT'

export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const GET_EXECUTE_TASK = 'GET_EXECUTE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
